On DEBUG FLUSHALL change reply to clients blocked on GETJOB.
As @djanowski suggested it is not a good idea to send them an
error: the client needs to handle a different corner case. We just reply
with the NULL reply we send on timeout, since this is part of the client
implementation anyway.